
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ccppas
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    repositories:
      auditing:
        enabled: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  mvc:
#    format:
#      date: dd-MM-yyyy